version: '3'
services:
  speechrecon:
    build: .
    container_name: VoiceAI
    restart: always
    volumes:
      - ./waves:/app/waves
      - ./trained:/app/trained
      - ./config:/app/config      
    ports:
      - "5100:5000"

